// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using is_lab6.Models;

namespace is_lab6.Migrations
{
    [DbContext(typeof(is_arch6Context))]
    [Migration("20231113070003_FillData")]
    partial class FillData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("is_lab6.Models.ShopItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemColor")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ItemLifetime")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("item_name");

                    b.Property<long>("ItemPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("item_price");

                    b.Property<string>("ItemStats")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("item_stats");

                    b.Property<string>("ItemWeight")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("TypeCode")
                        .HasColumnType("int");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.HasIndex("TypeCode");

                    b.HasIndex(new[] { "ItemName" }, "item_name_UNIQUE")
                        .IsUnique();

                    b.ToTable("shop_items");
                });

            modelBuilder.Entity("is_lab6.Models.Types", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Code");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("is_lab6.Models.ShopItem", b =>
                {
                    b.HasOne("is_lab6.Models.Types", "Type")
                        .WithMany("ShopItems")
                        .HasForeignKey("TypeCode");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("is_lab6.Models.Types", b =>
                {
                    b.Navigation("ShopItems");
                });
#pragma warning restore 612, 618
        }
    }
}
